### ISSUE TITLE
是否对子查询语法支持

### ISSUE THREAD

**Issue by liuyitian0** [RoundYuanYuan/spark-field-lineage#1]
想请教下是否对子查询或 union all 语法的支持？

**Comment by RoundYuanYuan** [comment]
有段时间没搞了，直接解析的的抽象语法书，我记得是支持的

**Comment by RoundYuanYuan** [comment]
> 想请教下是否对子查询或 union all 语法的支持？

有段时间没搞了，我当时记得是支持的，当时大多数常见语法都测试了
